# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, default=100, max_digits=4294967296),
            preserve_default=False,
        ),
    ]
