# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170108_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
