# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='local_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=4294967296),
        ),
        migrations.AddField(
            model_name='product',
            name='outside_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=4294967296),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_from',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='worldwide_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingcountry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
