# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_usershop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartentry',
            options={'verbose_name_plural': 'cart entries'},
        ),
        migrations.AlterModelOptions(
            name='shippingcountry',
            options={'verbose_name_plural': 'shipping countries'},
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='shipping_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=4294967296),
        ),
    ]
