# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipped_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PhysicalAddress'),
        ),
    ]
