# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170115_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
