# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_redeeming_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unlimited_stock',
            field=models.BooleanField(default=False),
        ),
    ]
