# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170115_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkeyset',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
