# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_userextra_authy_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='authy_verified',
            new_name='authenticator_verified',
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='authy_id',
        ),
        migrations.AddField(
            model_name='userextra',
            name='authenticator_id',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
