# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_purchaseitem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='donedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
