# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20170124_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0.995, max_digits=4294967296),
        ),
    ]
