# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='allowto',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='verifyemail',
            name='verify_url',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
