# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='physical',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
