# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
