# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import shop.cryptomethods


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_wallet_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=shop.cryptomethods.new_address, max_length=34),
        ),
    ]
