# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_purchase_shipped_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='can_customcss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usershop',
            name='customcss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usershop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
