# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_unlimited_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=shop.models.get_protected_file_path)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
