# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_digitalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalfile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
