# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_digitalfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_purchase_multiple',
            field=models.BooleanField(default=True),
        ),
    ]
