# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_can_purchase_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalKeySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='keyset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.DigitalKeySet'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PurchaseItem'),
        ),
    ]
