# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_digitalkeyset_is_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.TextField(default='')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PurchaseItem')),
            ],
        ),
    ]
