# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_shippingupdate_short_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='authy_id',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
