# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_userextra_authy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='authy_verified',
            field=models.BooleanField(default=False),
        ),
    ]
