# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20170122_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cached_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=4294967296, null=True),
        ),
    ]
