# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20170122_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cached_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=4294967296, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cached_shipping',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=4294967296, null=True),
        ),
    ]
