# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20170122_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_lastupdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
