# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_productimage_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='delete',
            new_name='uuid',
        ),
    ]
