# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20170123_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
