# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_purchaseitem_donedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='done',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='donedate',
        ),
        migrations.AddField(
            model_name='shippingupdate',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
