# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0049_purchaseitem_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('review', models.TextField(default='')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(default=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cached_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=65536, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cached_shipping',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=65536, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cached_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=65536, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='local_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='product',
            name='outside_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0.995, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='shipping_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=65536),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='redeemed',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=65536),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
